development:
  adapter: postgresql
  encoding: unicode
  database: sites_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: sites_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: sites_production
  pool: 5
  username:
  password:
